[env]
TERM = "xterm-256color"

[general]
import = [ "~/.config/alacritty/catppuccin-latte.toml" ]

[font]
normal = { family = "DejaVuSansM Nerd Font" }
size = 16

[window]
decorations = "None"
padding.x = 4
padding.y = 4
